title: Lebenslauf
description:  Lebenslauf von Svilen Mirchev 
url: https://mirchevsvilen.github.io/Lebenslauf
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
